# - Try to find the OpenMesh library
#

find_path(OPENMESH_INCLUDE_DIR NAMES OpenMesh/Core/System/config.h PATHS ${CONAN_INCLUDE_DIRS_OPENMESH})
find_library(OPENMESH_CORE_LIB NAMES OpenMeshCore OpenMeshCored PATHS ${CONAN_LIB_DIRS_OPENMESH})
find_library(OPENMESH_TOOLS_LIB NAMES OpenMeshTools OpenMeshToolsd PATHS ${CONAN_LIB_DIRS_OPENMESH})

set(OPENMESH_FOUND TRUE)
set(OPENMESH_INCLUDE_DIRS ${OPENMESH_INCLUDE_DIR})
set(OPENMESH_LIBRARIES ${OPENMESH_CORE_LIB} ${OPENMESH_TOOLS_LIB})
mark_as_advanced(OPENMESH_LIBRARY OPENMESH_INCLUDE_DIR)
